### ISSUE TITLE
Upload working directory structure in a new branch?

### ISSUE THREAD

**Issue by Unloaded123456** [Abstrat-Technologies/rustedanvil#19]
### Discussed in https://github.com/Abstrat-Technologies/rustedanvil/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **Unloaded123456** February 13, 2023</sup>
If Forge #965 can run, there should be a directory structure, with this, people would put the necessary files and make the stuff work! {it does not matter how much time it would take, if you have a working MDK installation, uploading directory structure in the early stages of the project would be good}. 
</div>

**Comment by arek-kwapis** [comment]
If you mean for the missing files, this is already covered in #15 and #16. If you mean for Forge & MCP, there isn't a point as they autogenerate their items.

I also do not have the time to do this currently. My focus is on trying to get this project finished. Additional things, like this, are far from a priority. If it was to be done, it won't be by me.

**Comment by Unloaded123456** [comment]
I mean the structure and names of the folders, not an additional file nor missing files:

> TheMasterCaver: If somebody still has an old working installation surely they could upload at least the directory structure so all the files could be manually put together, or a script made to download them using modern links (not sure of the legality of distributing an entire working Forge MDK environment, minus the Minecraft jar and decompiled files, of course, but the directory structure should be enough). In particular, I've been using the same decompiled MCP installation (1.6.4, non-Forge) for nearly 9 years (installed 12/17/2013; last decompiled 3/12/2014); at first I cleaned up/decompiled it to refresh the sources but then I made a copy of the src folder so I can copy them back over if needed; when moving to a new computer I copied the entire MCP folder over, instead of reinstalling it from scratch, so I know that will work.

**Comment by arek-kwapis** [comment]
All the files that need to be downloaded are already documented in the issues I listed. Everything else is autogenerated.

Like I said already, I'm not going to do this. I don't have the time.
