### ISSUE TITLE
Forge 1345?

### ISSUE THREAD

**Issue by Unloaded123456** [Abstrat-Technologies/rustedanvil#24]
Is there a problem about 1345 that makes unfixable or is fixing 965 easier?

**Comment by arek-kwapis** [comment]
I started with 965 as its what my mod pack runs on, however 1345 does have a few minor differences. Whenever that means it's easier or harder to fix I don't know. I could always try update 1345 too in the future.

**Comment by Unloaded123456** [comment]
My modpack runs on 1.7.10 1614, because that is the MDK version that I use. Looks like 1.7.10 will continue to work for years.
