### ISSUE TITLE
Porting to Gradle

### ISSUE THREAD

**Issue by Unloaded123456** [Abstrat-Technologies/rustedanvil#25]
**Is your feature request related to a problem? Please describe.**
Python scripts are more difficult to use than Gradle commands. 

**Describe the solution you'd like**
Porting 965 to Gradle.

**Describe alternatives you've considered**
Adding a "install" script

**Additional context**
N/A

**Comment by arek-kwapis** [comment]
I find the reverse is true - python is easier than gradle. However, regardless, this would be well outside the scope of this project. If you want it converted to gradle, you should be looking at the RetroGradle project. The most we'll do in the future is attempt to convert gradle to python, but we will never do the other way around.
