### ISSUE TITLE
Files disappeared

### ISSUE THREAD

**Issue by Unloaded123456** [Abstrat-Technologies/rustedanvil#28]
**Describe the bug**
After the last commit, the all scripts has been disappeared.

**To Reproduce**
Looking at the 1.6.4 - 965 branch. 

**Expected behavior**
All scripts existed. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by arek-kwapis** [comment]
This isn't a bug - it's intended. See #21

**Comment by Unloaded123456** [comment]
If it is not a bug, the "bug" label should be removed
