### ISSUE TITLE
[CORE][BUG] Build failure

### ISSUE THREAD

**Issue by arek-kwapis** [Abstrat-Technologies/rustedanvil#33]
**Describe the bug**
npm is unable to successfully build from the core due to a error with dependencies 

**To Reproduce**
`npm ci`

**Expected behavior**
[Return check with pass](https://i.imgur.com/CjPff80.png)

**Screenshots**
[Screen 1](https://i.imgur.com/56jVosx.png)

**Additional context**
Build scrips included to stop exactly this

of note is the weird behaviour of the modules, took 3 reinstalls before it behaved

**Comment by Unloaded123456** [comment]
Dependecies of what? Of NPM or Forge or something else?

**Comment by arek-kwapis** [comment]
> Dependecies of what? Of NPM or Forge or something else?

of the project.

Edit: It doesn't matter anyway. I'm now switching the testing infrastructure to use JEST instead.

**Comment by arek-kwapis** [comment]
Fixed in [105ae08](https://github.com/Abstrat-Technologies/rustedanvil-core/commit/105ae08764ce2d57f3c8de61fedef348552a3dbe)
